AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "A template to create the GOV.UK One login Account backend infrastructure."

Parameters:
  Environment:
    Description: "The environment type"
    Type: "String"
    AllowedValues:
      - "dev"
      - "build"
    Default: dev
    ConstraintDescription: must be dev or build
  VpcStackName:
    Description: >
      The name of the stack that defines the VPC in which this container will
      run.
    Type: String
    Default: vpc-enhanced
  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"
  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"

Mappings:
  AccountManagementUI:
    dev:
      url: "https://home.dev.account.gov.uk"
    build:
      url: "https://home.build.account.gov.uk"
  TxmaDummyInputQueue:
    dev:
      QueueArn: "arn:aws:sqs:eu-west-2:985326104449:account-mgmt-backend-TxMAInputDummyQueue-2nXfeOxQGy3g"
      KeyArn: "arn:aws:kms:eu-west-2:985326104449:key/6acd497a-65fc-464d-9d88-adaa34dad4cf"
      QueueUrl: "https://sqs.eu-west-2.amazonaws.com/985326104449/account-mgmt-backend-TxMAInputDummyQueue-2nXfeOxQGy3g"
    build:
      QueueArn: "arn:aws:sqs:eu-west-2:301577035144:account-mgmt-backend-TxMAInputDummyQueue-yWYwdmAuecBo"
      KeyArn: "arn:aws:kms:eu-west-2:301577035144:key/844ec710-0c1b-4455-8532-c5c7658298e3"
      QueueUrl: "https://sqs.eu-west-2.amazonaws.com/301577035144/account-mgmt-backend-TxMAInputDummyQueue-yWYwdmAuecBo"

Conditions:
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"

  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue

Resources:

  ######################################
  # Encryption
  ######################################
  LambdaKMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:*"
            Resource:
              - "*"
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action:
              - "kms:Decrypt"
            Resource: "*"

  LambdaKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}/${Environment}/LambdaKMSKey"
      TargetKeyId: !Ref LambdaKMSKey

  LoggingKmsKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource: "*"
            Condition:
              ArnLike:
                "kms:EncryptionContext:aws:logs:arn": !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"

  ######################################
  # Account Management API Stub
  ######################################
  AccountManagementStubFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - AccountManagementStubFunctionLogGroup
    Properties:
      FunctionName: !Sub ${Environment}-${AWS::StackName}-account-management-api-stub
      Architectures: ["arm64"]
      CodeUri: ../account-management-api/
      Handler: account-management-api-stub.handler
      KmsKeyArn: !GetAtt LambdaKMSKey.Arn
      PackageType: Zip
      MemorySize: 128
      ReservedConcurrentExecutions: 5
      Runtime: nodejs18.x
      Role: !GetAtt AccountManagementStubFunctionRole.Arn
      Timeout: 5
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdB
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-AWSServicesEndpointSecurityGroupId
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - account-management-api-stub.ts

  AccountManagementStubFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"

  AccountManagementStubApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: AccountManagementStubApi
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - HEAD
          - OPTIONS
          - POST
      Target: !GetAtt AccountManagementStubFunction.Arn

  AccountManagementStubApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref AccountManagementStubFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AccountManagementStubApi}/*"

  AccountManagementStubFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Environment}-${AWS::StackName}-account-management-api-stub"
      RetentionInDays: 30
      KmsKeyId: !GetAtt LoggingKmsKey.Arn

  AccountManagementStubApiEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The API Gateway endpoint for the Account Management stub
      Name: !Sub "/${AWS::StackName}/Stub/AccountManagement/Endpoint"
      Type: String
      Value: !GetAtt AccountManagementStubApi.ApiEndpoint

  ######################################
  # OIDC Authorization API Stub
  ######################################
  OidcAuthorizeApiStubFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - OidcAuthorizeApiStubFunctionLogGroup
    Properties:
      FunctionName: !Sub ${Environment}-${AWS::StackName}-oidc-authorize-stub
      Architectures: ["arm64"]
      CodeUri: ../oidc/authorize/
      Handler: oidc-authorize-stub.handler
      KmsKeyArn: !GetAtt LambdaKMSKey.Arn
      PackageType: Zip
      MemorySize: 128
      ReservedConcurrentExecutions: 5
      Runtime: nodejs18.x
      Role: !GetAtt OidcAuthorizeApiStubFunctionRole.Arn
      Timeout: 5
      Environment:
        Variables:
          DUMMY_TXMA_QUEUE_URL: !FindInMap [TxmaDummyInputQueue, !Ref Environment, QueueUrl]
          ACCOUNT_MANAGEMENT_URL: !FindInMap [AccountManagementUI, !Ref Environment, url]
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdB
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-AWSServicesEndpointSecurityGroupId
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - oidc-authorize-stub.ts

  OidcAuthorizeApiStubFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !Ref OidcAuthorizeApiStubPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"

  OidcAuthorizeApiStubFunctionApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: OidcAuthorizeApiStubFunctionApi
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - HEAD
          - OPTIONS
          - POST
      Target: !GetAtt OidcAuthorizeApiStubFunction.Arn

  OidcAuthorizeApiStubPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref OidcAuthorizeApiStubFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${OidcAuthorizeApiStubFunctionApi}/*"

  OidcAuthorizeApiStubFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Environment}-${AWS::StackName}-oidc-authorize-api-stub"
      RetentionInDays: 30
      KmsKeyId: !GetAtt LoggingKmsKey.Arn

  OidcAuthorizeApiStubEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The API Gateway endpoint for the Account Management stub
      Name: !Sub "/${AWS::StackName}/Stub/OIDC/authorize"
      Type: String
      Value: !GetAtt OidcAuthorizeApiStubFunctionApi.ApiEndpoint

  OidcAuthorizeApiStubPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !FindInMap [TxmaDummyInputQueue, !Ref Environment, QueueArn]
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Resource: !FindInMap [TxmaDummyInputQueue, !Ref Environment, KeyArn]

  ######################################
  # OIDC UserInfo API Stub
  ######################################
  OidcUserInfoApiStubFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - OidcUserInfoApiStubFunctionLogGroup
    Properties:
      FunctionName: !Sub ${Environment}-${AWS::StackName}-oidc-userinfo-stub
      Architectures: ["arm64"]
      CodeUri: ../oidc/userinfo/
      Handler: oidc-userinfo-stub.handler
      KmsKeyArn: !GetAtt LambdaKMSKey.Arn
      PackageType: Zip
      MemorySize: 128
      ReservedConcurrentExecutions: 5
      Runtime: nodejs18.x
      Role: !GetAtt OidcUserInfoApiStubFunctionRole.Arn
      Timeout: 5
      Events:
        userinfo:
          Type: Api
          Properties:
            Path: /userinfo
            Method: GET
            RestApiId:
              Ref: RestApi
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdB
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-AWSServicesEndpointSecurityGroupId
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - oidc-userinfo-stub.ts

  OidcUserInfoApiStubFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !Ref OidcAuthorizeApiStubPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"

  OidcUserInfoApiStubFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Environment}-${AWS::StackName}-oidc-userinfo-api-stub"
      RetentionInDays: 30
      KmsKeyId: !GetAtt LoggingKmsKey.Arn

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: HTTP API to emulate a token issuer for authorization in non-prod environments
      StageName: !Ref Environment
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
      MethodSettings:
        - HttpMethod: '*'
          CachingEnabled: true
          ResourcePath: /*
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayApiLogGroup.Arn

  ApiGatewayApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${RestApi}"
      RetentionInDays: 1
      KmsKeyId: !GetAtt LoggingKmsKey.Arn
